### ISSUE TITLE
Script Support for cromite browser

### ISSUE THREAD

**Issue by Solovertical** [LetrixZ/hentainexus-downloader-userscript#3]
Can you add support for Cromite browser (https://github.com/uazo/cromite) as well.
These are some script that work in cromite https://d3ward.github.io/kiwihub/userscripts.html

**Comment by LetrixZ** [comment]
Are you on Desktop or Android?

You can install Tampermonkey or Violentmonkey extension to use this script.

**Comment by Solovertical** [comment]
> Are you on Desktop or Android?
> 
> You can install Tampermonkey or Violentmonkey extension to use this script.

I am using android browser and there no way to install tamperamonkey in cromite and if you install, it just don't work, that why they have inbuilt script support for that. I tried nexus script and it didn't work.
